### ISSUE TITLE
Geeting error after Upgrade to 1.0.4 "Failed to validate the credentials from cookie"

### ISSUE THREAD

**Issue by nicx** [gcobb321/icloud3#44]
Hi, I get this error for each icloud3 device:

```
2019-06-11 15:28:23 ERROR (SyncWorker_17) [pyicloud.base.http] Failed to validate the credentials from cookie
2019-06-11 15:28:23 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Failed to validate the credentials from cookie'))
2019-06-11 15:28:23 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] No ICLOUD_ACCOUNTS added
2019-06-11 15:28:23 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
2019-06-11 15:28:23 ERROR (SyncWorker_0) [pyicloud.base.http] Failed to validate the credentials from cookie
2019-06-11 15:28:23 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Failed to validate the credentials from cookie'))
2019-06-11 15:28:23 ERROR (SyncWorker_0) [custom_components.icloud3.device_tracker] No ICLOUD_ACCOUNTS added
2019-06-11 15:28:23 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
```

What should I do?

**Comment by bryeartem** [comment]
I also got this issue last night... But was already on .94 for a few days.. but either way going back to 93.2 seemed to fix it for me...

**Comment by gcobb321** [comment]
I am now getting the same error. Trying to figure out what is going on and will post an update when I resolve the problem. I'm running HA v0.94.0

**Comment by bryeartem** [comment]
I thought it was something I did because it was around the same time I changed something in pyicloud to fix my lost iPhone issue ... glad to know It wasn’t me

**Comment by gcobb321** [comment]
It's getting the same error for the plain vanilla 'icloud' component so HA 0.94.0 broke something. I believe it has to do with reauthorizing the account.

**Comment by bryeartem** [comment]
Is it something to do with this?  I also had a “legacy” platform message as well ... https://github.com/home-assistant/home-assistant/pull/23862

**Comment by gcobb321** [comment]
I believe it is.

**Comment by bryeartem** [comment]
This seems to work but I’m way work so can’t do much testing .. https://github.com/PeterHedley94/pyicloud/commit/6bf11c87c784fa9b0f94318ea845e441b0937cf5

**Comment by riemers** [comment]
Same deal now too.. 
```
2019-06-13 20:42:39 ERROR (SyncWorker_3) [pyicloud.base.http] Failed to validate the credentials from cookie
```
Presume we will have to wait for the py cloud part to get an update.

**Comment by gcobb321** [comment]
Fixed in v1.0.5

**Comment by nicx** [comment]
I updated to version 1.0.6 today but still have an error, the device tracker is not added in HA. anything I missed?

**Comment by strfn** [comment]
Same issue here also with 1.0.5.

**Comment by gcobb321** [comment]
Make sure you have used the *include_devices* configuration parameter to specify the names of the devices to be tracked. Remember, the iCloud account cannot be accessed so the *include_device_type*  or fig parameter cannot be used. Go [here](https://github.com/gcobb321/icloud3#user-account-and-device-configuration-items) for more information.

**Comment by nicx** [comment]
I already have this option configured since the beginning of using your add-on ;)

here is my config which was working for months now:

```
  - platform: icloud3
    username: !secret icloud_user 
    password: !secret icloud_password
    account_name: user_icloud
    include_device: iphoneuser
    distance_method: calc
```

this is what I get in the log file:

```
2019-06-26 22:18:25 ERROR (SyncWorker_2) [pyicloud.base.http] Failed to validate the credentials from cookie
2019-06-26 22:18:25 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error authenticating iCloud Service for ***/user_icloud
2019-06-26 22:18:25 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] Error returned from pyicloud: ('Invalid email/password combination.', PyiCloudAPIResponseError('Failed to validate the credentials from cookie'))
2019-06-26 22:18:25 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] iCloud location service has been disabled
```

but as far as I understood this error is OK because of the changed iCloud auth issue.

How could I reset everything iCloud3 related to get my devices back running? Or any other idea what I could do?

**Comment by gcobb321** [comment]
1. Make sure you have the latest version of iCloud3 (v1.0.6) uploaded yesterday. Get it [here](https://github.com/gcobb321/icloud3/releases)
2. Make sure you are using the Home Assistant ios App v1.5
3. Wait until pyicloud is fixed.

**Comment by nicx** [comment]
1. I am using 1.0.6 -> check
2. I am using 1.5.1 -> check
3. As far as I understood this is only to get the iCloud auth function working again, has nothing todo with my missing device trackers in HA.

So how can I get back my device trackers even without iCloud location service running? That is my question ;)

**Comment by nicx** [comment]
Oh sh***, I found the problem: I commented the device out in the known devices yawl because of all the tests regarding iCloud auth issue. I reversed this change and everything is working again. Sorry for that :)

**Comment by gcobb321** [comment]
Sorry but I don't have an answer to that one. I guess it would be check logs during startup, check for Lovelace errors, check entities in developers tools, check entity register and Ios integrations, check to see if the iCloud3 sensors are being setup, check known_devices.yaml.

I had just finished this when your post came through. Glad it's working again.

**Comment by DBa2016** [comment]
@gcobb321 - do you think it would make sense to re-open this issue and keep it in "pending" state until iCloud auth works?

**Comment by gcobb321** [comment]
No need to. I worked on it all weekend and actually have it running now with new code. The only issue I see now (hopefully) is the notification from Apple that “you have logged into your your iCloud account from a city near you and if you want to allow it” followed by a 6-digit token.  The account is logged out of if there has been no activity for an X amount of time so it is logged back into and the notification is displayed again. I figured away around that last night and hope to get that fixed today or tomorrow. I’m hoping that I can have some beta code by the end of the week.

**Comment by riemers** [comment]
Nice work, i also noticed somewhere you mentioned that you can do a request update via a push message towards the ios app. If the daily limit of 100 wasn't a problem would that be a good alternative too? (although that might only be handy for single persons, if you have 4 devices its a lot)

Also keep in mind with IOS13 they will merge find my iphone and find friends together which make brake stuff again.
